# Generated by Django 2.1.2 on 2021-03-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('precipitation', models.CharField(max_length=200)),
                ('temp_min', models.CharField(max_length=200)),
                ('temp_max', models.CharField(max_length=200)),
                ('snowfall', models.CharField(max_length=200)),
            ],
        ),
    ]
